const express = require("express");
const {verifyToken} = require("../middleware/authMiddleware");
const eventsModel = require("../models/eventsModel");
const router = express.Router();

    router.post('/createEvent', verifyToken, eventsModel.createEvent);
    router.get('/', eventsModel.getAllEvents);
    router.patch('/update/:eventId', verifyToken, eventsModel.updateEvent);
    router.delete('/delete/:eventId', verifyToken, eventsModel.deleteEvent);
    router.get('/search', verifyToken, eventsModel.searchEvents);
    router.patch('/likes/:eventId', eventsModel.incrementLikeCount);
    router.patch('/dislikes/:eventId', eventsModel.incrementDislikeCount);
    router.patch('/views/:id', eventsModel.incrementViewCount);
    router.get("/eventsbyviews",eventsModel.get10EventsSortedByViews);
    router.get("/eventsbydatepagination", eventsModel.getAllEventsSortedByDateCreatedPagination);
    router.get("/eventsbydate", eventsModel.getAllEventsSortedByDateCreated);
    router.get('/getEvent/:id', eventsModel.getEventById);
    router.get('/eventsByTag/:id', eventsModel.getEventsByTag);
    router.get('/relatedEvents/:eventId', eventsModel.getRelatedEvents);
    router.get('/topReactions', eventsModel.getTopReactions);
    router.get('/eventsByCategory/:categoryId', eventsModel.getEventsByCategory);
    module.exports = router;